### ISSUE TITLE
Question about `nb4oea70`: too little short code

### ISSUE THREAD

**Issue by The-Lum** [plantuml/pdiff#2]
Hi @arnaudroques,

Could you have a look on:
https://github.com/plantuml/pdiff/blob/07c692461393f10f22512723ed5eab33a35fb649/db/nb/nb4oea70obc3r9hnnfju4d2lmopfm93.puml#L1-L11

Is it linked or not to:
- https://forum.plantuml.net/13595/latex-little-bug-when-processing-annotations-missing-space?show=13601#c13601

It seems a little short:
```puml
@startuml
foo
@enduml
```
not? :-) 😃 

Regards,
Th.

**Comment by arnaudroques** [comment]
We have bulk-added existing tests, and the referenced URL was indeed completely wrong.

Therefore, we have removed it. However, the test still makes sense for non-regression purposes: we are simply testing that this diagram should fail for every PlantUML version :-)

Thanks for pointing this out!
