### ISSUE TITLE
[cute] Question about `cute` diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/pdiff#3]
Hello @arnaudroques,

Here is a minor question:
- What is `cute` diagram?
- Is it public or private?
_Because if it is private, or not exposed: may be unnecessary to overload the tests with KO or not working tests..._
	
See list here:
- [_list of `@startcute` on `pdiff`_](https://github.com/search?q=repo%3Aplantuml%2Fpdiff+%40startcute&type=code)

Regards,
Th.

**Comment by arnaudroques** [comment]
> * What is `cute` diagram

A `cute` diagram was an older feature that allowed users to create basic drawings. This feature was removed a long time ago, so we have just removed any remaining references to it.

Thank you for pointing this out!

**Comment by The-Lum** [comment]
Hi,

_[Just for the record]_
That corresponding of this commit:
- ca2ed0f1

_Thanks @arnaudroques,_
Regards,
Th.
